<?php
$title='Quản lý nhiệm vụ Traffic';require_once realpath($_SERVER['DOCUMENT_ROOT']).'/cpanel/views/header.php';require_once realpath($_SERVER['DOCUMENT_ROOT']).'/cpanel/views/sidebar.php';require_once APP_ROOT.'/libs/traffic.php';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf_token();$action=(string)($_POST['action']??'');
 if($action==='provider'){require_superadmin(false);$provider=(string)$_POST['provider'];$token=trim((string)$_POST['api_token']);if(!in_array($provider,['link4m','layma','link2m'],true)||$token==='')exit('<script>alert("Provider/token không hợp lệ");history.back();</script>');$enc=encryptData($token);$exists=$db->get_row("SELECT id FROM traffic_providers WHERE provider='".$provider."'");if($exists)$db->update('traffic_providers',['api_token'=>$enc,'active'=>1,'updated_at'=>date('Y-m-d H:i:s')],"id='".(int)$exists['id']."'");else $db->insert('traffic_providers',['provider'=>$provider,'api_token'=>$enc,'active'=>1,'updated_at'=>date('Y-m-d H:i:s')]);exit('<script>alert("Đã lưu token an toàn");location.href="/cpanel/traffic";</script>');}
 if($action==='task'){$titleTask=trim((string)$_POST['title']);$url=trim((string)$_POST['destination_url']);$provider=(string)$_POST['provider'];if($titleTask===''||!filter_var($url,FILTER_VALIDATE_URL))exit('<script>alert("Thiếu tên hoặc URL");history.back();</script>');$db->insert('traffic_tasks',['title'=>$titleTask,'keyword'=>trim((string)$_POST['keyword']),'destination_url'=>$url,'backup_url'=>trim((string)$_POST['backup_url']),'provider'=>$provider,'reward'=>max(0,(int)$_POST['reward']),'wait_seconds'=>max(10,(int)$_POST['wait_seconds']),'instructions'=>trim((string)$_POST['instructions']),'status'=>1,'created_by'=>$data_user['id'],'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')]);exit('<script>alert("Đã tạo nhiệm vụ");location.href="/cpanel/traffic";</script>');}
 if($action==='review'){$sid=(int)$_POST['submission_id'];$decision=(string)$_POST['decision'];$db->query('START TRANSACTION');$s=$db->get_row("SELECT * FROM traffic_submissions WHERE id='".$sid."' FOR UPDATE");if(!$s||$s['status']!=='pending'){$db->query('ROLLBACK');exit('<script>alert("Yêu cầu không còn chờ duyệt");history.back();</script>');}if($decision==='approve'){$ok=PlusCredits($s['user_id'],$s['reward'],'Thưởng nhiệm vụ Traffic #'.$s['task_id'],'TRAFFIC_'.$sid);if(!$ok){$db->query('ROLLBACK');exit('<script>alert("Cộng thưởng thất bại");history.back();</script>');}$db->update('traffic_submissions',['status'=>'approved','admin_note'=>trim((string)$_POST['admin_note']),'reviewed_at'=>date('Y-m-d H:i:s')],"id='".$sid."'");}else{$db->update('traffic_submissions',['status'=>'rejected','admin_note'=>trim((string)$_POST['admin_note']),'reviewed_at'=>date('Y-m-d H:i:s')],"id='".$sid."'");}$db->query('COMMIT');exit('<script>alert("Đã xử lý");location.href="/cpanel/traffic";</script>');}
}
$tasks=$db->get_list('SELECT * FROM traffic_tasks ORDER BY id DESC LIMIT 50');$pending=$db->get_list("SELECT s.*,t.title,u.username FROM traffic_submissions s JOIN traffic_tasks t ON t.id=s.task_id JOIN users u ON u.id=s.user_id WHERE s.status='pending' ORDER BY s.id ASC");
?>
<main id="main-container"><div class="content"><h2>Nhiệm vụ Traffic</h2>
<?php if(is_superadmin_account($data_user)):?><div class="block block-rounded"><div class="block-header"><h3 class="block-title">API Providers</h3></div><div class="block-content"><form method="post" class="row g-2"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars(generate_csrf_token(),ENT_QUOTES)?>"><input type="hidden" name="action" value="provider"><div class="col-md-3"><select name="provider" class="form-control"><option>link4m</option><option>layma</option><option>link2m</option></select></div><div class="col-md-7"><input type="password" name="api_token" class="form-control" placeholder="API token mới (không dùng token đã lộ)" required></div><div class="col-md-2"><button class="btn btn-primary">Lưu token</button></div></form></div></div><?php endif;?>
<div class="block block-rounded"><div class="block-header"><h3 class="block-title">Tạo nhiệm vụ</h3></div><div class="block-content"><form method="post" class="row g-2"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars(generate_csrf_token(),ENT_QUOTES)?>"><input type="hidden" name="action" value="task"><div class="col-md-4"><input class="form-control" name="title" placeholder="Tên nhiệm vụ" required></div><div class="col-md-4"><input class="form-control" name="keyword" placeholder="Từ khóa tìm kiếm"></div><div class="col-md-4"><select class="form-control" name="provider"><option>link4m</option><option>layma</option><option>link2m</option></select></div><div class="col-md-6"><input class="form-control" type="url" name="destination_url" placeholder="URL đích" required></div><div class="col-md-6"><input class="form-control" type="url" name="backup_url" placeholder="URL dự phòng (LAYMA)"></div><div class="col-md-3"><input class="form-control" type="number" min="0" name="reward" placeholder="Tiền thưởng"></div><div class="col-md-3"><input class="form-control" type="number" min="10" name="wait_seconds" value="60"></div><div class="col-md-6"><input class="form-control" name="instructions" placeholder="Hướng dẫn"></div><div class="col-12"><button class="btn btn-success">Tạo nhiệm vụ</button></div></form></div></div>
<div class="block block-rounded"><div class="block-header"><h3 class="block-title">Chờ duyệt (<?=count($pending)?>)</h3></div><div class="block-content table-responsive"><table class="table"><tr><th>User</th><th>Nhiệm vụ</th><th>Minh chứng</th><th>Thưởng</th><th>Duyệt</th></tr><?php foreach($pending as $s):?><tr><td><?=htmlspecialchars($s['username'],ENT_QUOTES)?></td><td><?=htmlspecialchars($s['title'],ENT_QUOTES)?></td><td><?=nl2br(htmlspecialchars($s['proof'],ENT_QUOTES))?></td><td><?=format_cash($s['reward'])?>đ</td><td><form method="post"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars(generate_csrf_token(),ENT_QUOTES)?>"><input type="hidden" name="action" value="review"><input type="hidden" name="submission_id" value="<?=$s['id']?>"><input name="admin_note" placeholder="Ghi chú"><button name="decision" value="approve" class="btn btn-sm btn-success">Duyệt</button><button name="decision" value="reject" class="btn btn-sm btn-danger">Từ chối</button></form></td></tr><?php endforeach;?></table></div></div>
</div></main><?php require_once realpath($_SERVER['DOCUMENT_ROOT']).'/cpanel/views/footer.php';?>
