<?php
require_once realpath($_SERVER['DOCUMENT_ROOT']).'/libs/init.php';require_once APP_ROOT.'/libs/traffic.php';
if($_SERVER['REQUEST_METHOD']!=='POST'){http_response_code(405);exit(JsonMsg('error','Method Not Allowed'));}if(!$user)exit(JsonMsg('error','Vui lòng đăng nhập'));
$posted=(string)($_POST['csrf_token']??'');if(!hash_equals((string)($_SESSION['csrf_token']??''),$posted)){header('HTTP/1.1 419 Authentication Timeout',true,419);exit(JsonMsg('error','Invalid CSRF'));}
$userId=(int)$data_user['id'];$action=(string)($_POST['action']??'');$amount=max(0,(int)($_POST['amount']??0));
$db->query('START TRANSACTION');$wallet=$db->get_row("SELECT * FROM traffic_wallets WHERE user_id='".$userId."' FOR UPDATE");$balance=(int)($wallet['balance']??0);
if($amount<=0||$amount>$balance){$db->query('ROLLBACK');exit(JsonMsg('error','Số tiền không hợp lệ hoặc vượt quá số dư nhiệm vụ'));}
if($action==='transfer'){$ok=$db->query("UPDATE traffic_wallets SET balance=balance-'".$amount."',updated_at=NOW() WHERE user_id='".$userId."'")!==false;$ok=$db->cong('users','money',$amount,"`id`='".$userId."'")!==false&&$ok;if(!$ok){$db->query('ROLLBACK');exit(JsonMsg('error','Chuyển số dư thất bại'));}$db->insert('log_balance',['trans_id'=>'TRAFFIC_TRANSFER_'.time().'_'.$userId,'money_before'=>$data_user['money'],'money_change'=>$amount,'money_after'=>$data_user['money']+$amount,'time'=>gettime(),'type'=>'+','content'=>'Chuyển từ số dư nhiệm vụ','user_id'=>$userId]);create_user_notification($userId,'transaction','Chuyển số dư nhiệm vụ thành công','Đã chuyển '.format_cash($amount).'đ vào số dư chính','/customer/balance');$db->query('COMMIT');exit(JsonMsg('success','Đã chuyển '.format_cash($amount).'đ vào số dư chính'));}
if($action==='withdraw'){$min=traffic_min_withdraw();$bank=trim((string)($_POST['bank_name']??''));$number=trim((string)($_POST['account_number']??''));$name=trim((string)($_POST['account_name']??''));if($amount<$min||$bank===''||$number===''||$name===''){$db->query('ROLLBACK');exit(JsonMsg('error','Tối thiểu '.format_cash($min).'đ và phải nhập đủ thông tin ngân hàng'));}$ok=$db->query("UPDATE traffic_wallets SET balance=balance-'".$amount."',updated_at=NOW() WHERE user_id='".$userId."'")!==false;$ok=$db->insert('traffic_withdrawals',['user_id'=>$userId,'amount'=>$amount,'bank_name'=>$bank,'account_number'=>$number,'account_name'=>$name,'status'=>'pending','created_at'=>date('Y-m-d H:i:s')])&&$ok;if(!$ok){$db->query('ROLLBACK');exit(JsonMsg('error','Tạo yêu cầu rút tiền thất bại'));}$db->query('COMMIT');exit(JsonMsg('success','Đã gửi yêu cầu rút tiền, vui lòng chờ admin xử lý'));}
$db->query('ROLLBACK');exit(JsonMsg('error','Thao tác không hợp lệ'));
